import CSS from 'csstype'
import { Breakpoint } from '@common/utils'

export type PropBreakpoint = Breakpoint | number
export type CSSPropertyValue<PropTypes> =
  | {
      [key in PropBreakpoint]?: PropTypes
    }
  | PropTypes

export type CustomCSSProps = {
  p?: CSSPropertyValue<CSS.Property.Padding>
  pt?: CSSPropertyValue<CSS.Property.PaddingTop>
  pb?: CSSPropertyValue<CSS.Property.PaddingBottom>
  pl?: CSSPropertyValue<CSS.Property.PaddingLeft>
  pr?: CSSPropertyValue<CSS.Property.PaddingRight>
  py?:
    | CSSPropertyValue<CSS.Property.PaddingTop>
    | CSSPropertyValue<CSS.Property.PaddingBottom>
  px?:
    | CSSPropertyValue<CSS.Property.PaddingLeft>
    | CSSPropertyValue<CSS.Property.PaddingRight>
  m?: CSSPropertyValue<CSS.Property.Margin>
  mt?: CSSPropertyValue<CSS.Property.MarginTop>
  mb?: CSSPropertyValue<CSS.Property.MarginBottom>
  ml?: CSSPropertyValue<CSS.Property.MarginLeft>
  mr?: CSSPropertyValue<CSS.Property.MarginRight>
  my?:
    | CSSPropertyValue<CSS.Property.MarginTop>
    | CSSPropertyValue<CSS.Property.MarginBottom>
  mx?:
    | CSSPropertyValue<CSS.Property.MarginLeft>
    | CSSPropertyValue<CSS.Property.MarginRight>
  w?: CSSPropertyValue<CSS.Property.Width>
  minW?: CSSPropertyValue<CSS.Property.MinWidth>
  maxW?: CSSPropertyValue<CSS.Property.MaxWidth>
  h?: CSSPropertyValue<CSS.Property.Height>
  minH?: CSSPropertyValue<CSS.Property.MinHeight>
  maxH?: CSSPropertyValue<CSS.Property.MaxHeight>
  boxSize?:
    | CSSPropertyValue<CSS.Property.Width>
    | CSSPropertyValue<CSS.Property.Width>
  bgColor?: CSSPropertyValue<CSS.Property.BackgroundColor>
  bgGradient?: CSSPropertyValue<CSS.Property.BackgroundImage>
  bgClip?: CSSPropertyValue<CSS.Property.BackgroundClip>
  borderX?:
    | CSSPropertyValue<CSS.Property.BorderLeft>
    | CSSPropertyValue<CSS.Property.BorderRight>
  borderY?:
    | CSSPropertyValue<CSS.Property.BorderTop>
    | CSSPropertyValue<CSS.Property.BorderBottom>
}
export type CSSProps = {
  accentColor?: CSSPropertyValue<CSS.Property.AccentColor>
  alignContent?: CSSPropertyValue<CSS.Property.AlignContent>
  alignItems?: CSSPropertyValue<CSS.Property.AlignItems>
  alignSelf?: CSSPropertyValue<CSS.Property.AlignSelf>
  alignTracks?: CSSPropertyValue<CSS.Property.AlignTracks>
  animationComposition?: CSSPropertyValue<CSS.Property.AnimationComposition>
  animationDelay?: CSSPropertyValue<CSS.Property.AnimationDelay>
  animationDirection?: CSSPropertyValue<CSS.Property.AnimationDirection>
  animationDuration?: CSSPropertyValue<CSS.Property.AnimationDuration>
  animationFillMode?: CSSPropertyValue<CSS.Property.AnimationFillMode>
  animationIterationCount?: CSSPropertyValue<CSS.Property.AnimationIterationCount>
  animationName?: CSSPropertyValue<CSS.Property.AnimationName>
  animationPlayState?: CSSPropertyValue<CSS.Property.AnimationPlayState>
  animationTimeline?: CSSPropertyValue<CSS.Property.AnimationTimeline>
  animationTimingFunction?: CSSPropertyValue<CSS.Property.AnimationTimingFunction>
  appearance?: CSSPropertyValue<CSS.Property.Appearance>
  aspectRatio?: CSSPropertyValue<CSS.Property.AspectRatio>
  backdropFilter?: CSSPropertyValue<CSS.Property.BackdropFilter>
  backfaceVisibility?: CSSPropertyValue<CSS.Property.BackfaceVisibility>
  backgroundAttachment?: CSSPropertyValue<CSS.Property.BackgroundAttachment>
  backgroundBlendMode?: CSSPropertyValue<CSS.Property.BackgroundBlendMode>
  backgroundClip?: CSSPropertyValue<CSS.Property.BackgroundClip>
  backgroundColor?: CSSPropertyValue<CSS.Property.BackgroundColor>
  backgroundImage?: CSSPropertyValue<CSS.Property.BackgroundImage>
  backgroundOrigin?: CSSPropertyValue<CSS.Property.BackgroundOrigin>
  backgroundPositionX?: CSSPropertyValue<CSS.Property.BackgroundPositionX>
  backgroundPositionY?: CSSPropertyValue<CSS.Property.BackgroundPositionY>
  backgroundRepeat?: CSSPropertyValue<CSS.Property.BackgroundRepeat>
  backgroundSize?: CSSPropertyValue<CSS.Property.BackgroundSize>
  blockOverflow?: CSSPropertyValue<CSS.Property.BlockOverflow>
  blockSize?: CSSPropertyValue<CSS.Property.BlockSize>
  borderBlockColor?: CSSPropertyValue<CSS.Property.BorderBlockColor>
  borderBlockEndColor?: CSSPropertyValue<CSS.Property.BorderBlockEndColor>
  borderBlockEndStyle?: CSSPropertyValue<CSS.Property.BorderBlockEndStyle>
  borderBlockEndWidth?: CSSPropertyValue<CSS.Property.BorderBlockEndWidth>
  borderBlockStartColor?: CSSPropertyValue<CSS.Property.BorderBlockStartColor>
  borderBlockStartStyle?: CSSPropertyValue<CSS.Property.BorderBlockStartStyle>
  borderBlockStartWidth?: CSSPropertyValue<CSS.Property.BorderBlockStartWidth>
  borderBlockStyle?: CSSPropertyValue<CSS.Property.BorderBlockStyle>
  borderBlockWidth?: CSSPropertyValue<CSS.Property.BorderBlockWidth>
  borderBottomColor?: CSSPropertyValue<CSS.Property.BorderBottomColor>
  borderBottomLeftRadius?: CSSPropertyValue<CSS.Property.BorderBottomLeftRadius>
  borderBottomRightRadius?: CSSPropertyValue<CSS.Property.BorderBottomRightRadius>
  borderBottomStyle?: CSSPropertyValue<CSS.Property.BorderBottomStyle>
  borderBottomWidth?: CSSPropertyValue<CSS.Property.BorderBottomWidth>
  borderCollapse?: CSSPropertyValue<CSS.Property.BorderCollapse>
  borderEndEndRadius?: CSSPropertyValue<CSS.Property.BorderEndEndRadius>
  borderEndStartRadius?: CSSPropertyValue<CSS.Property.BorderEndStartRadius>
  borderImageOutset?: CSSPropertyValue<CSS.Property.BorderImageOutset>
  borderImageRepeat?: CSSPropertyValue<CSS.Property.BorderImageRepeat>
  borderImageSlice?: CSSPropertyValue<CSS.Property.BorderImageSlice>
  borderImageSource?: CSSPropertyValue<CSS.Property.BorderImageSource>
  borderImageWidth?: CSSPropertyValue<CSS.Property.BorderImageWidth>
  borderInlineColor?: CSSPropertyValue<CSS.Property.BorderInlineColor>
  borderInlineEndColor?: CSSPropertyValue<CSS.Property.BorderInlineEndColor>
  borderInlineEndStyle?: CSSPropertyValue<CSS.Property.BorderInlineEndStyle>
  borderInlineEndWidth?: CSSPropertyValue<CSS.Property.BorderInlineEndWidth>
  borderInlineStartColor?: CSSPropertyValue<CSS.Property.BorderInlineStartColor>
  borderInlineStartStyle?: CSSPropertyValue<CSS.Property.BorderInlineStartStyle>
  borderInlineStartWidth?: CSSPropertyValue<CSS.Property.BorderInlineStartWidth>
  borderInlineStyle?: CSSPropertyValue<CSS.Property.BorderInlineStyle>
  borderInlineWidth?: CSSPropertyValue<CSS.Property.BorderInlineWidth>
  borderLeftColor?: CSSPropertyValue<CSS.Property.BorderLeftColor>
  borderLeftStyle?: CSSPropertyValue<CSS.Property.BorderLeftStyle>
  borderLeftWidth?: CSSPropertyValue<CSS.Property.BorderLeftWidth>
  borderRightColor?: CSSPropertyValue<CSS.Property.BorderRightColor>
  borderRightStyle?: CSSPropertyValue<CSS.Property.BorderRightStyle>
  borderRightWidth?: CSSPropertyValue<CSS.Property.BorderRightWidth>
  borderSpacing?: CSSPropertyValue<CSS.Property.BorderSpacing>
  borderStartEndRadius?: CSSPropertyValue<CSS.Property.BorderStartEndRadius>
  borderStartStartRadius?: CSSPropertyValue<CSS.Property.BorderStartStartRadius>
  borderTopColor?: CSSPropertyValue<CSS.Property.BorderTopColor>
  borderTopLeftRadius?: CSSPropertyValue<CSS.Property.BorderTopLeftRadius>
  borderTopRightRadius?: CSSPropertyValue<CSS.Property.BorderTopRightRadius>
  borderTopStyle?: CSSPropertyValue<CSS.Property.BorderTopStyle>
  borderTopWidth?: CSSPropertyValue<CSS.Property.BorderTopWidth>
  bottom?: CSSPropertyValue<CSS.Property.Bottom>
  boxDecorationBreak?: CSSPropertyValue<CSS.Property.BoxDecorationBreak>
  boxShadow?: CSSPropertyValue<CSS.Property.BoxShadow>
  boxSizing?: CSSPropertyValue<CSS.Property.BoxSizing>
  breakAfter?: CSSPropertyValue<CSS.Property.BreakAfter>
  breakBefore?: CSSPropertyValue<CSS.Property.BreakBefore>
  breakInside?: CSSPropertyValue<CSS.Property.BreakInside>
  captionSide?: CSSPropertyValue<CSS.Property.CaptionSide>
  caretColor?: CSSPropertyValue<CSS.Property.CaretColor>
  clear?: CSSPropertyValue<CSS.Property.Clear>
  clipPath?: CSSPropertyValue<CSS.Property.ClipPath>
  color?: CSSPropertyValue<CSS.Property.Color>
  colorAdjust?: CSSPropertyValue<CSS.Property.PrintColorAdjust>
  colorScheme?: CSSPropertyValue<CSS.Property.ColorScheme>
  columnCount?: CSSPropertyValue<CSS.Property.ColumnCount>
  columnFill?: CSSPropertyValue<CSS.Property.ColumnFill>
  columnGap?: CSSPropertyValue<CSS.Property.ColumnGap>
  columnRuleColor?: CSSPropertyValue<CSS.Property.ColumnRuleColor>
  columnRuleStyle?: CSSPropertyValue<CSS.Property.ColumnRuleStyle>
  columnRuleWidth?: CSSPropertyValue<CSS.Property.ColumnRuleWidth>
  columnSpan?: CSSPropertyValue<CSS.Property.ColumnSpan>
  columnWidth?: CSSPropertyValue<CSS.Property.ColumnWidth>
  contain?: CSSPropertyValue<CSS.Property.Contain>
  content?: CSSPropertyValue<CSS.Property.Content>
  contentVisibility?: CSSPropertyValue<CSS.Property.ContentVisibility>
  counterIncrement?: CSSPropertyValue<CSS.Property.CounterIncrement>
  counterReset?: CSSPropertyValue<CSS.Property.CounterReset>
  counterSet?: CSSPropertyValue<CSS.Property.CounterSet>
  cursor?: CSSPropertyValue<CSS.Property.Cursor>
  direction?: CSSPropertyValue<CSS.Property.Direction>
  display?: CSSPropertyValue<CSS.Property.Display>
  emptyCells?: CSSPropertyValue<CSS.Property.EmptyCells>
  filter?: CSSPropertyValue<CSS.Property.Filter>
  flexBasis?: CSSPropertyValue<CSS.Property.FlexBasis>
  flexDirection?: CSSPropertyValue<CSS.Property.FlexDirection>
  flexGrow?: CSSPropertyValue<CSS.Property.FlexGrow>
  flexShrink?: CSSPropertyValue<CSS.Property.FlexShrink>
  flexWrap?: CSSPropertyValue<CSS.Property.FlexWrap>
  float?: CSSPropertyValue<CSS.Property.Float>
  fontFamily?: CSSPropertyValue<CSS.Property.FontFamily>
  fontFeatureSettings?: CSSPropertyValue<CSS.Property.FontFeatureSettings>
  fontKerning?: CSSPropertyValue<CSS.Property.FontKerning>
  fontLanguageOverride?: CSSPropertyValue<CSS.Property.FontLanguageOverride>
  fontOpticalSizing?: CSSPropertyValue<CSS.Property.FontOpticalSizing>
  fontSize?: CSSPropertyValue<CSS.Property.FontSize>
  fontSizeAdjust?: CSSPropertyValue<CSS.Property.FontSizeAdjust>
  fontSmooth?: CSSPropertyValue<CSS.Property.FontSmooth>
  fontStretch?: CSSPropertyValue<CSS.Property.FontStretch>
  fontStyle?: CSSPropertyValue<CSS.Property.FontStyle>
  fontSynthesis?: CSSPropertyValue<CSS.Property.FontSynthesis>
  fontVariant?: CSSPropertyValue<CSS.Property.FontVariant>
  fontVariantAlternates?: CSSPropertyValue<CSS.Property.FontVariantAlternates>
  fontVariantCaps?: CSSPropertyValue<CSS.Property.FontVariantCaps>
  fontVariantEastAsian?: CSSPropertyValue<CSS.Property.FontVariantEastAsian>
  fontVariantLigatures?: CSSPropertyValue<CSS.Property.FontVariantLigatures>
  fontVariantNumeric?: CSSPropertyValue<CSS.Property.FontVariantNumeric>
  fontVariantPosition?: CSSPropertyValue<CSS.Property.FontVariantPosition>
  fontVariationSettings?: CSSPropertyValue<CSS.Property.FontVariationSettings>
  fontWeight?: CSSPropertyValue<CSS.Property.FontWeight>
  forcedColorAdjust?: CSSPropertyValue<CSS.Property.ForcedColorAdjust>
  gridAutoColumns?: CSSPropertyValue<CSS.Property.GridAutoColumns>
  gridAutoFlow?: CSSPropertyValue<CSS.Property.GridAutoFlow>
  gridAutoRows?: CSSPropertyValue<CSS.Property.GridAutoRows>
  gridColumnEnd?: CSSPropertyValue<CSS.Property.GridColumnEnd>
  gridColumnStart?: CSSPropertyValue<CSS.Property.GridColumnStart>
  gridRowEnd?: CSSPropertyValue<CSS.Property.GridRowEnd>
  gridRowStart?: CSSPropertyValue<CSS.Property.GridRowStart>
  gridTemplateAreas?: CSSPropertyValue<CSS.Property.GridTemplateAreas>
  gridTemplateColumns?: CSSPropertyValue<CSS.Property.GridTemplateColumns>
  gridTemplateRows?: CSSPropertyValue<CSS.Property.GridTemplateRows>
  hangingPunctuation?: CSSPropertyValue<CSS.Property.HangingPunctuation>
  height?: CSSPropertyValue<CSS.Property.Height>
  hyphenateCharacter?: CSSPropertyValue<CSS.Property.HyphenateCharacter>
  hyphens?: CSSPropertyValue<CSS.Property.Hyphens>
  imageOrientation?: CSSPropertyValue<CSS.Property.ImageOrientation>
  imageRendering?: CSSPropertyValue<CSS.Property.ImageRendering>
  imageResolution?: CSSPropertyValue<CSS.Property.ImageResolution>
  initialLetter?: CSSPropertyValue<CSS.Property.InitialLetter>
  inlineSize?: CSSPropertyValue<CSS.Property.InlineSize>
  inputSecurity?: CSSPropertyValue<CSS.Property.InputSecurity>
  inset?: CSSPropertyValue<CSS.Property.Inset>
  insetBlock?: CSSPropertyValue<CSS.Property.InsetBlock>
  insetBlockEnd?: CSSPropertyValue<CSS.Property.InsetBlockEnd>
  insetBlockStart?: CSSPropertyValue<CSS.Property.InsetBlockStart>
  insetInline?: CSSPropertyValue<CSS.Property.InsetInline>
  insetInlineEnd?: CSSPropertyValue<CSS.Property.InsetInlineEnd>
  insetInlineStart?: CSSPropertyValue<CSS.Property.InsetInlineStart>
  isolation?: CSSPropertyValue<CSS.Property.Isolation>
  justifyContent?: CSSPropertyValue<CSS.Property.JustifyContent>
  justifyItems?: CSSPropertyValue<CSS.Property.JustifyItems>
  justifySelf?: CSSPropertyValue<CSS.Property.JustifySelf>
  justifyTracks?: CSSPropertyValue<CSS.Property.JustifyTracks>
  left?: CSSPropertyValue<CSS.Property.Left>
  letterSpacing?: CSSPropertyValue<CSS.Property.LetterSpacing>
  lineBreak?: CSSPropertyValue<CSS.Property.LineBreak>
  lineHeight?: CSSPropertyValue<CSS.Property.LineHeight>
  lineHeightStep?: CSSPropertyValue<CSS.Property.LineHeightStep>
  listStyleImage?: CSSPropertyValue<CSS.Property.ListStyleImage>
  listStylePosition?: CSSPropertyValue<CSS.Property.ListStylePosition>
  listStyleType?: CSSPropertyValue<CSS.Property.ListStyleType>
  marginBlock?: CSSPropertyValue<CSS.Property.MarginBlock>
  marginBlockEnd?: CSSPropertyValue<CSS.Property.MarginBlockEnd>
  marginBlockStart?: CSSPropertyValue<CSS.Property.MarginBlockStart>
  marginBottom?: CSSPropertyValue<CSS.Property.MarginBottom>
  marginInline?: CSSPropertyValue<CSS.Property.MarginInline>
  marginInlineEnd?: CSSPropertyValue<CSS.Property.MarginInlineEnd>
  marginInlineStart?: CSSPropertyValue<CSS.Property.MarginInlineStart>
  marginLeft?: CSSPropertyValue<CSS.Property.MarginLeft>
  marginRight?: CSSPropertyValue<CSS.Property.MarginRight>
  marginTop?: CSSPropertyValue<CSS.Property.MarginTop>
  maskBorderMode?: CSSPropertyValue<CSS.Property.MaskBorderMode>
  maskBorderOutset?: CSSPropertyValue<CSS.Property.MaskBorderOutset>
  maskBorderRepeat?: CSSPropertyValue<CSS.Property.MaskBorderRepeat>
  maskBorderSlice?: CSSPropertyValue<CSS.Property.MaskBorderSlice>
  maskBorderSource?: CSSPropertyValue<CSS.Property.MaskBorderSource>
  maskBorderWidth?: CSSPropertyValue<CSS.Property.MaskBorderWidth>
  maskClip?: CSSPropertyValue<CSS.Property.MaskClip>
  maskComposite?: CSSPropertyValue<CSS.Property.MaskComposite>
  maskImage?: CSSPropertyValue<CSS.Property.MaskImage>
  maskMode?: CSSPropertyValue<CSS.Property.MaskMode>
  maskOrigin?: CSSPropertyValue<CSS.Property.MaskOrigin>
  maskPosition?: CSSPropertyValue<CSS.Property.MaskPosition>
  maskRepeat?: CSSPropertyValue<CSS.Property.MaskRepeat>
  maskSize?: CSSPropertyValue<CSS.Property.MaskSize>
  maskType?: CSSPropertyValue<CSS.Property.MaskType>
  mathDepth?: CSSPropertyValue<CSS.Property.MathDepth>
  mathShift?: CSSPropertyValue<CSS.Property.MathShift>
  mathStyle?: CSSPropertyValue<CSS.Property.MathStyle>
  maxBlockSize?: CSSPropertyValue<CSS.Property.MaxBlockSize>
  maxHeight?: CSSPropertyValue<CSS.Property.MaxHeight>
  maxInlineSize?: CSSPropertyValue<CSS.Property.MaxInlineSize>
  maxLines?: CSSPropertyValue<CSS.Property.MaxLines>
  maxWidth?: CSSPropertyValue<CSS.Property.MaxWidth>
  minBlockSize?: CSSPropertyValue<CSS.Property.MinBlockSize>
  minHeight?: CSSPropertyValue<CSS.Property.MinHeight>
  minInlineSize?: CSSPropertyValue<CSS.Property.MinInlineSize>
  minWidth?: CSSPropertyValue<CSS.Property.MinWidth>
  mixBlendMode?: CSSPropertyValue<CSS.Property.MixBlendMode>
  motionDistance?: CSSPropertyValue<CSS.Property.OffsetDistance>
  motionPath?: CSSPropertyValue<CSS.Property.OffsetPath>
  motionRotation?: CSSPropertyValue<CSS.Property.OffsetRotate>
  objectFit?: CSSPropertyValue<CSS.Property.ObjectFit>
  objectPosition?: CSSPropertyValue<CSS.Property.ObjectPosition>
  offsetAnchor?: CSSPropertyValue<CSS.Property.OffsetAnchor>
  offsetDistance?: CSSPropertyValue<CSS.Property.OffsetDistance>
  offsetPath?: CSSPropertyValue<CSS.Property.OffsetPath>
  offsetRotate?: CSSPropertyValue<CSS.Property.OffsetRotate>
  offsetRotation?: CSSPropertyValue<CSS.Property.OffsetRotate>
  opacity?: CSSPropertyValue<CSS.Property.Opacity>
  order?: CSSPropertyValue<CSS.Property.Order>
  orphans?: CSSPropertyValue<CSS.Property.Orphans>
  outlineColor?: CSSPropertyValue<CSS.Property.OutlineColor>
  outlineOffset?: CSSPropertyValue<CSS.Property.OutlineOffset>
  outlineStyle?: CSSPropertyValue<CSS.Property.OutlineStyle>
  outlineWidth?: CSSPropertyValue<CSS.Property.OutlineWidth>
  overflowAnchor?: CSSPropertyValue<CSS.Property.OverflowAnchor>
  overflowBlock?: CSSPropertyValue<CSS.Property.OverflowBlock>
  overflowClipBox?: CSSPropertyValue<CSS.Property.OverflowClipBox>
  overflowClipMargin?: CSSPropertyValue<CSS.Property.OverflowClipMargin>
  overflowInline?: CSSPropertyValue<CSS.Property.OverflowInline>
  overflowWrap?: CSSPropertyValue<CSS.Property.OverflowWrap>
  overflowX?: CSSPropertyValue<CSS.Property.OverflowX>
  overflowY?: CSSPropertyValue<CSS.Property.OverflowY>
  overscrollBehaviorBlock?: CSSPropertyValue<CSS.Property.OverscrollBehaviorBlock>
  overscrollBehaviorInline?: CSSPropertyValue<CSS.Property.OverscrollBehaviorInline>
  overscrollBehaviorX?: CSSPropertyValue<CSS.Property.OverscrollBehaviorX>
  overscrollBehaviorY?: CSSPropertyValue<CSS.Property.OverscrollBehaviorY>
  paddingBlock?: CSSPropertyValue<CSS.Property.PaddingBlock>
  paddingBlockEnd?: CSSPropertyValue<CSS.Property.PaddingBlockEnd>
  paddingBlockStart?: CSSPropertyValue<CSS.Property.PaddingBlockStart>
  paddingBottom?: CSSPropertyValue<CSS.Property.PaddingBottom>
  paddingInline?: CSSPropertyValue<CSS.Property.PaddingInline>
  paddingInlineEnd?: CSSPropertyValue<CSS.Property.PaddingInlineEnd>
  paddingInlineStart?: CSSPropertyValue<CSS.Property.PaddingInlineStart>
  paddingLeft?: CSSPropertyValue<CSS.Property.PaddingLeft>
  paddingRight?: CSSPropertyValue<CSS.Property.PaddingRight>
  paddingTop?: CSSPropertyValue<CSS.Property.PaddingTop>
  pageBreakAfter?: CSSPropertyValue<CSS.Property.PageBreakAfter>
  pageBreakBefore?: CSSPropertyValue<CSS.Property.PageBreakBefore>
  pageBreakInside?: CSSPropertyValue<CSS.Property.PageBreakInside>
  paintOrder?: CSSPropertyValue<CSS.Property.PaintOrder>
  perspective?: CSSPropertyValue<CSS.Property.Perspective>
  perspectiveOrigin?: CSSPropertyValue<CSS.Property.PerspectiveOrigin>
  placeContent?: CSSPropertyValue<CSS.Property.PlaceContent>
  pointerEvents?: CSSPropertyValue<CSS.Property.PointerEvents>
  position?: CSSPropertyValue<CSS.Property.Position>
  printColorAdjust?: CSSPropertyValue<CSS.Property.PrintColorAdjust>
  quotes?: CSSPropertyValue<CSS.Property.Quotes>
  resize?: CSSPropertyValue<CSS.Property.Resize>
  right?: CSSPropertyValue<CSS.Property.Right>
  rotate?: CSSPropertyValue<CSS.Property.Rotate>
  rowGap?: CSSPropertyValue<CSS.Property.RowGap>
  rubyAlign?: CSSPropertyValue<CSS.Property.RubyAlign>
  rubyMerge?: CSSPropertyValue<CSS.Property.RubyMerge>
  rubyPosition?: CSSPropertyValue<CSS.Property.RubyPosition>
  scale?: CSSPropertyValue<CSS.Property.Scale>
  scrollBehavior?: CSSPropertyValue<CSS.Property.ScrollBehavior>
  scrollMargin?: CSSPropertyValue<CSS.Property.ScrollMargin>
  scrollMarginBlock?: CSSPropertyValue<CSS.Property.ScrollMarginBlock>
  scrollMarginBlockEnd?: CSSPropertyValue<CSS.Property.ScrollMarginBlockEnd>
  scrollMarginBlockStart?: CSSPropertyValue<CSS.Property.ScrollMarginBlockStart>
  scrollMarginBottom?: CSSPropertyValue<CSS.Property.ScrollMarginBottom>
  scrollMarginInline?: CSSPropertyValue<CSS.Property.ScrollMarginInline>
  scrollMarginInlineEnd?: CSSPropertyValue<CSS.Property.ScrollMarginInlineEnd>
  scrollMarginInlineStart?: CSSPropertyValue<CSS.Property.ScrollMarginInlineStart>
  scrollMarginLeft?: CSSPropertyValue<CSS.Property.ScrollMarginLeft>
  scrollMarginRight?: CSSPropertyValue<CSS.Property.ScrollMarginRight>
  scrollMarginTop?: CSSPropertyValue<CSS.Property.ScrollMarginTop>
  scrollPadding?: CSSPropertyValue<CSS.Property.ScrollPadding>
  scrollPaddingBlock?: CSSPropertyValue<CSS.Property.ScrollPaddingBlock>
  scrollPaddingBlockEnd?: CSSPropertyValue<CSS.Property.ScrollPaddingBlockEnd>
  scrollPaddingBlockStart?: CSSPropertyValue<CSS.Property.ScrollPaddingBlockStart>
  scrollPaddingBottom?: CSSPropertyValue<CSS.Property.ScrollPaddingBottom>
  scrollPaddingInline?: CSSPropertyValue<CSS.Property.ScrollPaddingInline>
  scrollPaddingInlineEnd?: CSSPropertyValue<CSS.Property.ScrollPaddingInlineEnd>
  scrollPaddingInlineStart?: CSSPropertyValue<CSS.Property.ScrollPaddingInlineStart>
  scrollPaddingLeft?: CSSPropertyValue<CSS.Property.ScrollPaddingLeft>
  scrollPaddingRight?: CSSPropertyValue<CSS.Property.ScrollPaddingRight>
  scrollPaddingTop?: CSSPropertyValue<CSS.Property.ScrollPaddingTop>
  scrollSnapAlign?: CSSPropertyValue<CSS.Property.ScrollSnapAlign>
  scrollSnapMargin?: CSSPropertyValue<CSS.Property.ScrollMargin>
  scrollSnapMarginBottom?: CSSPropertyValue<CSS.Property.ScrollMarginBottom>
  scrollSnapMarginLeft?: CSSPropertyValue<CSS.Property.ScrollMarginLeft>
  scrollSnapMarginRight?: CSSPropertyValue<CSS.Property.ScrollMarginRight>
  scrollSnapMarginTop?: CSSPropertyValue<CSS.Property.ScrollMarginTop>
  scrollSnapStop?: CSSPropertyValue<CSS.Property.ScrollSnapStop>
  scrollSnapType?: CSSPropertyValue<CSS.Property.ScrollSnapType>
  scrollbarColor?: CSSPropertyValue<CSS.Property.ScrollbarColor>
  scrollbarGutter?: CSSPropertyValue<CSS.Property.ScrollbarGutter>
  scrollbarWidth?: CSSPropertyValue<CSS.Property.ScrollbarWidth>
  shapeImageThreshold?: CSSPropertyValue<CSS.Property.ShapeImageThreshold>
  shapeMargin?: CSSPropertyValue<CSS.Property.ShapeMargin>
  shapeOutside?: CSSPropertyValue<CSS.Property.ShapeOutside>
  tabSize?: CSSPropertyValue<CSS.Property.TabSize>
  tableLayout?: CSSPropertyValue<CSS.Property.TableLayout>
  textAlign?: CSSPropertyValue<CSS.Property.TextAlign>
  textAlignLast?: CSSPropertyValue<CSS.Property.TextAlignLast>
  textCombineUpright?: CSSPropertyValue<CSS.Property.TextCombineUpright>
  textDecorationColor?: CSSPropertyValue<CSS.Property.TextDecorationColor>
  textDecorationLine?: CSSPropertyValue<CSS.Property.TextDecorationLine>
  textDecorationSkip?: CSSPropertyValue<CSS.Property.TextDecorationSkip>
  textDecorationSkipInk?: CSSPropertyValue<CSS.Property.TextDecorationSkipInk>
  textDecorationStyle?: CSSPropertyValue<CSS.Property.TextDecorationStyle>
  textDecorationThickness?: CSSPropertyValue<CSS.Property.TextDecorationThickness>
  textEmphasisColor?: CSSPropertyValue<CSS.Property.TextEmphasisColor>
  textEmphasisPosition?: CSSPropertyValue<CSS.Property.TextEmphasisPosition>
  textEmphasisStyle?: CSSPropertyValue<CSS.Property.TextEmphasisStyle>
  textIndent?: CSSPropertyValue<CSS.Property.TextIndent>
  textJustify?: CSSPropertyValue<CSS.Property.TextJustify>
  textOrientation?: CSSPropertyValue<CSS.Property.TextOrientation>
  textOverflow?: CSSPropertyValue<CSS.Property.TextOverflow>
  textRendering?: CSSPropertyValue<CSS.Property.TextRendering>
  textShadow?: CSSPropertyValue<CSS.Property.TextShadow>
  textSizeAdjust?: CSSPropertyValue<CSS.Property.TextSizeAdjust>
  textTransform?: CSSPropertyValue<CSS.Property.TextTransform>
  textUnderlineOffset?: CSSPropertyValue<CSS.Property.TextUnderlineOffset>
  textUnderlinePosition?: CSSPropertyValue<CSS.Property.TextUnderlinePosition>
  top?: CSSPropertyValue<CSS.Property.Top>
  touchAction?: CSSPropertyValue<CSS.Property.TouchAction>
  transform?: CSSPropertyValue<CSS.Property.Transform>
  transformBox?: CSSPropertyValue<CSS.Property.TransformBox>
  transformOrigin?: CSSPropertyValue<CSS.Property.TransformOrigin>
  transformStyle?: CSSPropertyValue<CSS.Property.TransformStyle>
  transitionDelay?: CSSPropertyValue<CSS.Property.TransitionDelay>
  transitionDuration?: CSSPropertyValue<CSS.Property.TransitionDuration>
  transitionProperty?: CSSPropertyValue<CSS.Property.Transition>
  transitionTimingFunction?: CSSPropertyValue<CSS.Property.TransitionTimingFunction>
  translate?: CSSPropertyValue<CSS.Property.Translate>
  unicodeBidi?: CSSPropertyValue<CSS.Property.UnicodeBidi>
  userSelect?: CSSPropertyValue<CSS.Property.UserSelect>
  verticalAlign?: CSSPropertyValue<CSS.Property.VerticalAlign>
  visibility?: CSSPropertyValue<CSS.Property.Visibility>
  whiteSpace?: CSSPropertyValue<CSS.Property.WhiteSpace>
  widows?: CSSPropertyValue<CSS.Property.Widows>
  width?: CSSPropertyValue<CSS.Property.Width>
  willChange?: CSSPropertyValue<CSS.Property.WillChange>
  wordBreak?: CSSPropertyValue<CSS.Property.WordBreak>
  wordSpacing?: CSSPropertyValue<CSS.Property.WordSpacing>
  wordWrap?: CSSPropertyValue<CSS.Property.WordWrap>
  writingMode?: CSSPropertyValue<CSS.Property.WritingMode>
  zIndex?: CSSPropertyValue<CSS.Property.ZIndex>
  zoom?: CSSPropertyValue<CSS.Property.Zoom>
}

export type CSSProperties = CSSProps & CustomCSSProps
